---
- name: install openjdk 8
  yum:
    # name: openjdk-8-jre
    name: java-1.8.0-openjdk-headless
    update_cache: yes
    state: present

- name: tools
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - net-tools
    - curl
    - lsof