---
- name: install openjdk 8
  yum:
    name: java-1.8.0-openjdk-headless
    state: present

- name: tools
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - net-tools
    - curl
    - lsof