---
- name: update yum
  raw: yum -y update

- name: install openjdk 8
  yum:
    name: java-1.8.0-openjdk-headless
    state: present

- name: tools
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - bind-utils
    - curl
    - lsof

# update system
- name: update system
  yum: name="*" state=latest

# create folder structure
- include_tasks: initialize_structure.yml

# open port & allow firewall 
- include_tasks: firewall_settings.yml