---
- name: add jenkins repo
  yum_repository:
    name: jenkins.repo
    baseurl: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    state: present

- name: add jenkins gpg key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: install jenkins
  yum:
    name: jenkins
    state: present

  # debug:
  #   msg: after_ran_handler