---
- name: install nginx
  apt:
    name: nginx
    state: present

# ufw does not allow to ssh after start, need to research more
# - name: add nginx to firewall
#   ufw:
#     rule: allow
#     name: Nginx Full
#     port: "{{ port_lists }}"
#     proto: tcp
    # state: enabled