---
- name: tools
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - net-tools
    - curl
    - lsof

- name: install openjdk 8
  apt:
    name: openjdk-8-jdk-headless
    update_cache: yes
    state: present


# - name: allow firewall rules
#   ufw:
#     name: openssh-server
#     rule: allow
#     port: 22
#     proto: tcp